version: '3.9'

services:
  db:
    image: postgres:15.3-alpine3.18
    ports:
      - 9001:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    restart: always
    volumes:
      - db-dev:/var/lib/postgresql/data
volumes:
  db-dev:
